export const LOAD_ARTICLE_LIST_FAILED_ACTION = 'LOAD_ARTICLE_LIST_FAILED_ACTION'
export const LOAD_ARTICLE_LIST_ACTION = 'LOAD_ARTICLE_LIST_ACTION'
export const LOAD_ARTICLE_LIST_SUCCESSED_ACTION = 'LOAD_ARTICLE_LIST_SUCCESSED_ACTION'
export const QUANTITY_CHANGED_ACTION = 'QUANTITY_CHANGED_ACTION'
export const QUANTITY_ON_PAGE = 10
